### PR TITLE
add missing observer for split updates

### PR DESCRIPTION
**Pull request by sgratzl**

### CODE REVIEW

**Comment by sgratzl** [comment]
> Is this related to the "adjust LineUp area" feature? How does this change the app's behavior?

it is a bugfix that the legend cannot be hidden anymore

**Comment by waxlamp** [comment]
> > Is this related to the "adjust LineUp area" feature? How does this change the app's behavior?
> 
> it is a bugfix that the legend cannot be hidden anymore

Can you describe the bug in some more detail? You're saying it used to be that by changing the table area you could corrupt the legend?

**Comment by waxlamp** [comment]
Thanks for the explanation.

**Comment by sgratzl** [comment]
probably also caused #143

**Pull request merged**
