### PR TITLE
proper dark mode

### PR DESCRIPTION
**Pull request by sgratzl**
Screenshot from 2019-09-11 08-54-27

Screenshot from 2019-09-11 08-54-04

### CODE REVIEW

**Comment by sgratzl** [comment]
you mean the overall stroke color of the points?

**Comment by sgratzl** [comment]
all strokes:

Screenshot from 2019-09-11 11-45-24

or should it just of the selected one?

**Comment by sgratzl** [comment]
with selection

image

**Comment by waxlamp** [comment]
Just on selection.

**Comment by sgratzl** [comment]
Screenshot from 2019-09-11 12-59-13

**Pull request merged**
