### PR TITLE
Make the control panel collapsible

### LINKED ISSUE #64: collapseable info panel
based on #61 the info panel is now to the right. Thus, making the settings panel on the left collapsible creates more space if needed

### PR DESCRIPTION
**Pull request by sgratzl**
based on #71  <-- change the to merge branch before merging back to master

closes #64 

open (default)
Screenshot from 2019-09-04 17-47-14

closed:
Screenshot from 2019-09-04 17-48-17

notes
 * I restructured the header a bit such that the proper toggling works
 * I fixed the resize issue of the renderer
 * I added the chosen dataset to the header

### CODE REVIEW

**Comment by sgratzl** [comment]
> Is there a way to stop the data display from "snapping" to a new position once the collapse/expand animation finishes?

so far there is an animation to show/hide the side panel. The resize observer of the scene manager will trigger then almost every other millisecond. Thus, by default it will resize and redraw all the time. To avoid that I added a simple debouncing which results in the jumping. I could remove the animation.

**Comment by waxlamp** [comment]
What if we just disable the resize observer for the duration of the animation?

**Comment by sgratzl** [comment]
> What if we just disable the resize observer for the duration of the animation?

sure will still jump after that, since the canvas needs to be resized, recentered, and redrawn

**Comment by waxlamp** [comment]
Ah right. Well I'd say let's just get rid of the animation then.

**Comment by sgratzl** [comment]
take a look at the current version, please. it works almost, except for some unknown reason it jumps like 5px briefly when showing the menu again.

**Pull request merged**
