### PR TITLE
Add deployment scripts

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by waxlamp** [comment]
@cjh1 thanks for this. If it's ready to fold in, go ahead and revoke the draft status and merge.

**Comment by waxlamp** [comment]
@cjh1 is this very old PR still valid, afayr? Thanks! :smile_cat:

**Comment by cjh1** [comment]
I would say its still valid ...

**Comment by waxlamp** [comment]
Thanks for confirming, @cjh1. I will go ahead and merge.

**Pull request merged**
